# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google_auth_migration.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bgoogle_auth_migration.proto\"\x8b\x01\n\x10MigrationPayload\x12&\n\x0eotp_parameters\x18\x01 \x03(\x0b\x32\x0e.OtpParameters\x12\x0f\n\x07version\x18\x02 \x01(\x05\x12\x12\n\nbatch_size\x18\x03 \x01(\x05\x12\x13\n\x0b\x62\x61tch_index\x18\x04 \x01(\x05\x12\x15\n\rtotal_batches\x18\x05 \x01(\x05\"\x8d\x01\n\rOtpParameters\x12\x0e\n\x06secret\x18\x01 \x01(\x0c\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06issuer\x18\x03 \x01(\t\x12!\n\x04type\x18\x04 \x01(\x0e\x32\x13.OtpParameters.Type\x12\x0f\n\x07\x63ounter\x18\x05 \x01(\x03\"\x1a\n\x04Type\x12\x08\n\x04HOTP\x10\x00\x12\x08\n\x04TOTP\x10\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'google_auth_migration_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MIGRATIONPAYLOAD._serialized_start=32
  _MIGRATIONPAYLOAD._serialized_end=171
  _OTPPARAMETERS._serialized_start=174
  _OTPPARAMETERS._serialized_end=315
  _OTPPARAMETERS_TYPE._serialized_start=289
  _OTPPARAMETERS_TYPE._serialized_end=315
# @@protoc_insertion_point(module_scope)